Also, we're not the DRG any more.

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -7,17 +7,17 @@ ROOT=`dirname $0`/..
 HAS_RAXREGION=false
 HAS_ANSIBLE=false
 HAS_PYRAX=false
-HAS_DRGSSH=false
+HAS_DEVEX=false
 HAS_PUBLISHERKEY=false
 
 [ -n "${RAX_REGION}" ] && HAS_RAXREGION=true
 (which ansible-playbook 2>&1 >/dev/null) && HAS_ANSIBLE=true
 python -c 'import pyrax' 2>/dev/null && HAS_PYRAX=true
-[ -f ${HOME}/.ssh/drg_rsa ] && HAS_DRGSSH=true
+[ -f ${HOME}/.ssh/devex_rsa ] && HAS_DEVEX=true
 [ -f ${ROOT}/deploy/roles/jenkins_master/files/var/lib/jenkins/publisher.id_rsa ] && HAS_PUBLISHERKEY=true
 
 if ! $HAS_RAXREGION || ! $HAS_ANSIBLE || ! $HAS_PYRAX ||
-    ! $HAS_DRGSSH || ! $HAS_PUBLISHERKEY ; then
+    ! $HAS_DEVEX || ! $HAS_PUBLISHERKEY ; then
   echo "Uh oh! You're missing some things you'll need to get started."
   echo
 
@@ -45,8 +45,8 @@ if ! $HAS_RAXREGION || ! $HAS_ANSIBLE || ! $HAS_PYRAX ||
     echo
   fi
 
-  if ! $HAS_DRGSSH ; then
-    echo "* The drg_rsa private key is missing."
+  if ! $HAS_DEVEX ; then
+    echo "* The devex_rsa private key is missing."
     echo "  Put it at ${HOME}/.ssh and chmod it 600."
     echo
   fi
